### ISSUE TITLE
Running OPM with hysteresis option

### ISSUE THREAD

**Issue by jeosol** [OPM/opm-tests#121]
Hi, 

I am trying to use OPM on a synthetic hysteresis example and was wondering if OPM works with the options described in the manual. Also, are there hysteresis specific examples I could look at. I am mostly interested in the set up. I was getting errors using the IMBNUM keywords as described in the manual. I suspect, I am doing something wrong and would like to see an example if you guys have one. Thanks

**Comment by atgeirr** [comment]
The Norne test case available in the opm-data repository uses hysteresis, and sets IMBNUM. Perhaps that can help.

**Comment by jeosol** [comment]
Thanks. That was helpful. I was able to fix the errors. 

P.S. Where you at the Olympus workshop last year in Barcelona, Spain.

**Comment by atgeirr** [comment]
> Thanks. That was helpful. I was able to fix the errors.

Good to hear! I'll close the issue.

> P.S. Where you at the Olympus workshop last year in Barcelona, Spain.

Yes, I was! Feel free to send me an email if you want to discuss further.
