### ISSUE TITLE
Master?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-tests#14]
Is master broken now, or is it my code:

https://ci.opm-project.org/job/opm-common-PR-builder/273/

**Comment by GitPaean** [comment]
Can you try it again? Maybe there are some delay between modules. 

It can be the merging of https://github.com/OPM/opm-simulators/pull/1477 and https://github.com/OPM/opm-tests/pull/13 caused the problem?

**Comment by akva2** [comment]
just unfortunate timing i believe. we had a similar error triggered in opm-simulators post builder but when i manually re-ran it, all was fine.

**Comment by GitPaean** [comment]
I  guess this issue is not relevant anymore, https://github.com/OPM/opm-common/pull/391 related was already merged.
