### ISSUE TITLE
Master and Reference Group Control Case Issues for Multi-Segement Wells

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-tests#823]
I refactored most of the model2 group cases, and then went about checking the results with the reference cases. There were differences for all of the multi-segment wells cases.  So I reran the original cases using the current master, and I still get differences for the multi-segment well cases. The standard well cases are the same, that is master and reference match.

Case GRUPCNTL-01, is the 0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_MSW.DATA cases, which is the simplest of all the cases. The configuration is:
```                                                        
                                                        FIELD
                                                          |
                                                     --------------
                                                      |           |
                                                    INJE        PROD
                                                     |            |
                                                   INJE1      -------- 
                                                              |        |
                                                             WGRP1    WGRP2
                                                               |       |
                                                           --------  PROD2
                                                           |      |
                                                        PROD1   PROD3
```

And in the following plots, the TST case is the master version and REF is the reference case.

Field production matches:
![Field_Production_Comparison_Plot](https://user-images.githubusercontent.com/17958927/195792757-3e218dd0-cf0d-428b-bcf3-71e357fc21a1.png)

Likewise for injection:
![Group_INJE_Water_Injection_Comparison_Plot](https://user-images.githubusercontent.com/17958927/195792957-2fb9ca71-0a4e-4e84-a739-ebcd691b582e.png)

Now for groups we have:
![Group_WGRP1_Production_Comparison_Plot](https://user-images.githubusercontent.com/17958927/195793119-10feb4e0-d904-471f-a42e-b7c826c1eadd.png)

![Group_WGRP2_Production_Comparison_Plot](https://user-images.githubusercontent.com/17958927/195793201-3d27c5fb-2bfe-4f67-96b2-ec01a3e86a4e.png)

And naturally the wells are different as well.

![Well_PROD1_Production_Performance](https://user-images.githubusercontent.com/17958927/195795418-991220fe-842f-4b14-8488-a3261b73c595.png)

![Well_PROD2_Production_Performance](https://user-images.githubusercontent.com/17958927/195795440-ec24ab2c-c22f-4891-9f5a-ff86bd893100.png)

![Well_PROD3_Production_Performance](https://user-images.githubusercontent.com/17958927/195795476-5dd98d02-20e1-42e5-8bbf-2a319f547265.png)

Now so which is the correct version, well running my refactored case on E100 (just because I have the results), the reference case is the correct solution, as you can see below for the two groups.

![Group_WGRP1_Production_Comparison_Plot](https://user-images.githubusercontent.com/17958927/195798044-e2f72cdd-f1ed-4ed9-b989-0cbe3891e06e.png)

![Group_WGRP2_Production_Comparison_Plot](https://user-images.githubusercontent.com/17958927/195798078-015bc66d-007a-4b84-bd7a-9de9e1ff3b9f.png)

And the wells are identical as well.

![Well_PROD1_Production_Performance](https://user-images.githubusercontent.com/17958927/195798180-0f6fcc3e-dae3-4e01-9265-f8ec2adbafb1.png)

![Well_PROD2_Production_Performance](https://user-images.githubusercontent.com/17958927/195798203-f7052353-3fa6-4810-9d6a-be8641a45176.png)

![Well_PROD3_Production_Performance](https://user-images.githubusercontent.com/17958927/195798229-b3b68ea4-1366-4762-b2bd-63fb27f58c0e.png)

So we have an issue with current master.

**Comment by tskille** [comment]
> So I reran the original cases using the current master

Did you then use option --solver-max-time-step-in-days=3 ? 

From the [regression testing setup](https://github.com/OPM/opm-simulators/blob/8162b97c0e417988c68663c44ea3ad8bb1b42863/compareECLFiles.cmake#L549) you will see that GRCTRL cases with MSW is run with 3 days maximum time steps. 

I checked the case 0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_MSW.DATA with Flow build from master this morning using max time step of 3 days, the reference summary files in model2/opm-simulation-reference/flow and with Eclipse100. These results shows good agreement.

**Comment by OPMUSER** [comment]
> Did you then use option --solver-max-time-step-in-days=3 ?

No I did not.

Previously I ran a bunch of cases using one day time steps to compare against E100 and 2022-04 - so not comparable. Let me rerun and check again with three day time steps and I'll get back to you.

**Comment by OPMUSER** [comment]
> Did you then use option --solver-max-time-step-in-days=3 ?

No I did not.

Previously I ran a bunch of cases using one day time steps to compare against E100 and 2022-04 - so not comparable. Let me rerun and check again with three day time steps and I'll get back to you.

**Comment by OPMUSER** [comment]
Okay, now everything matches using the default `TUNING` parameters for the standard wells and `TUNING(TSMAXZ) = 3` for the mult-segment wells. However, if I use one day time steps the standard wells are different, but the multi-segment wells are reasonable.

In the future we should try and avoid arbitrary values for  `TUNING(TSMAXZ)`. Either let the simulator select the time step size, or set it to one day to benchmark against the commercial simulator.

**Comment by alfbr** [comment]
> In the future we should try and avoid arbitrary values for `TUNING(TSMAXZ)`. Either let the simulator select the time step size, or set it to one day to benchmark against the commercial simulator.

Indeed, and that has been the case all along. Unfortunately, we have historically had severe difficulties in running some of the tests with default parameters. Especially for the cases with difficult convergence, we have periodically applied numerous tuning parameters just to have them reproducible. Actually, I do not remember why we ended up with the three day maximum here. If we can avoid it without degrading the quality of the test, then I believe everybody is positive to that.
