### ISSUE TITLE
SPE10 Model 1 does not run

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-tests#892]
Since we introduced stricter parsing, the model does not run.

**Comment by bska** [comment]
Confirmed.  Running [opm-tests/spe10/SPE10-MOD01-01](https://github.com/OPM/opm-tests/blob/b1d5a516cbf3af423a4a77097d4c31a2c0ba3962/spe10/SPE10-MOD01-01.DATA) I get the following diagnostic for the [`NONNC`](https://github.com/OPM/opm-tests/blob/b1d5a516cbf3af423a4a77097d4c31a2c0ba3962/spe10/SPE10-MOD01-01.DATA#L88) keyword
```
Error: Unsupported keywords or keyword items:

  NONNC: keyword not supported
  In file: /data-1/projects/models/opm-tests/spe10/SPE10-MOD01-01.DATA, line 88
```

**Comment by alfbr** [comment]
We need to decide, remove the keyword from the case, or support it.

**Comment by bska** [comment]
> remove the keyword from the case, or support it.

I don't think we get any benefit from our solver if we know that there are no non-neighbouring connections, so my vote would be to remove the keyword&ndash;at least from the SPE10 models (`MOD01-01`, `MOD01-02`, `MOD01-02`, `MOD02-01`, and `MOD02-02`).  The "SPIDER" and "RADIAL" cases in [`opm-tests/spe02`](https://github.com/OPM/opm-tests/tree/22fe1edf8f9effa777109a079e00d4a57d29aa3a/spe02) are a little less clear-cut to me.  In those cases, `NONNC` might conceivably change the simulation results. and we should not pretend we support that setup until we actually do.

**Comment by OPMUSER** [comment]
Unless I hear otherwise, I'll comment out the  `NONNC`  in all SPE10 cases.

**Comment by alfbr** [comment]
> Unless I hear otherwise, I'll comment out the `NONNC` in all SPE10 cases.

Yes, please do. Greatly appreciated!

**Comment by bska** [comment]
PR #894, which fixes this problem, was merged into the master branch.  I am now able to run `MOD01-01` (selected results below).  I've not tested the other models yet, but I believe this issue is resolved.  Please close if you agree, @alfbr.

---

![SPE10_MOD01_01](https://user-images.githubusercontent.com/1871438/218803652-46c50c0f-b2fa-4ff3-b4b5-e8f93cf739b9.png)

**Comment by bska** [comment]
I'm closing this now as "resolved".  There have been no reports concerning this issue for more than a year.
